-- ============================================================
-- 038 — Embedded Signup provenance on whatsapp_config
--
-- Under the Tech Provider model a client connects their WhatsApp by
-- clicking through Meta's Embedded Signup inside our app, instead of
-- pasting a Phone Number ID and a token they generated by hand. Both
-- paths end up in the same `whatsapp_config` row — `phone_number_id`,
-- `waba_id` and `access_token` already exist there since 001 — so this
-- migration only adds what Embedded Signup knows and the manual path
-- doesn't.
--
--   onboarded_via     'manual' (default, matches every existing row)
--                     or 'embedded_signup'
--   meta_business_id  the client's Meta Business Portfolio id, returned
--                     by the signup callback. Needed to tell two WABAs
--                     of the same client apart and to support later
--                     Tech-Provider-level calls.
--   waba_name         display name of the WABA, so the settings screen
--                     can say WHICH account is connected without an
--                     extra Graph round trip on every render.
--   onboarded_at      when the signup completed (connected_at already
--                     exists but is also touched by manual reconnects).
--
-- Deliberately NOT added: a token-expiry column. Embedded Signup under a
-- Tech Provider app yields a long-lived business token; storing a
-- computed expiry we don't refresh would be a lie that eventually
-- silently blocks sends. Token health is already surfaced by the
-- existing GET /api/whatsapp/config check.
--
-- Idempotent — safe to re-run.
-- ============================================================

ALTER TABLE public.whatsapp_config
  ADD COLUMN IF NOT EXISTS onboarded_via text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS meta_business_id text,
  ADD COLUMN IF NOT EXISTS waba_name text,
  ADD COLUMN IF NOT EXISTS onboarded_at timestamptz;

DO $$ BEGIN
  ALTER TABLE public.whatsapp_config
    ADD CONSTRAINT whatsapp_config_onboarded_via_check
    CHECK (onboarded_via IN ('manual', 'embedded_signup'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- One WABA can host several phone numbers, and a Tech Provider app sees
-- all of them. Inbound webhooks are routed by phone_number_id (which
-- already has a UNIQUE constraint from 013), so this index only speeds
-- up the admin-side "which accounts belong to this business" lookups.
CREATE INDEX IF NOT EXISTS idx_whatsapp_config_meta_business_id
  ON public.whatsapp_config (meta_business_id)
  WHERE meta_business_id IS NOT NULL;
